version: "3.9"

services:
  apache:
    build:
      context: ./docker/apache
      dockerfile: ./Dockerfile
    command: apache2-foreground
    volumes:
      - ./www/:/home/bitrix/www/
    networks:
      - bitrix

  db:
    image: mysql:5.7.41-debian
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: sitemanager
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrix
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bitrix

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    ports: 
      - "80:80"
    volumes:
      - ./www/:/home/bitrix/www/
    networks:
      - bitrix

volumes:
  mysql_data:

networks:
  bitrix:
    driver: bridge
