FROM nginx:alpine

ADD ./etc/nginx/nginx.conf /etc/nginx/nginx.conf
ADD ./etc/nginx/mime.types /etc/nginx/mime.types
ADD ./etc/nginx/bx/ /etc/nginx/bx/

ADD ./var/www/bitrixenv_error/ var/www/bitrixenv_error/
